name: Camel K Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Setup Camel K Tools
      uses: nicolaferraro/camel-k-github-action@2baed3211c2ded95681d8efbcbacac9cebc43072
      with:
        cluster: none
    - name: Connect to remote cluster
      env:
        OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
        OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
        OPENSHIFT_URL: ${{ secrets.OPENSHIFT_URL }}
      run: |
        oc login -u ${OPENSHIFT_USER} -p ${OPENSHIFT_PASSWORD} --server=${OPENSHIFT_URL} --insecure-skip-tls-verify
        oc project camel-k-basic-staging
    
    - name: Deploy Integrations
      run: |
        kamel install
        
        kamel run Basic.java

        oc delete secret routing-properties || true
        oc create secret generic routing-properties --from-file routing.properties
        kamel run Routing.java --secret routing-properties -d camel:bean
